### ISSUE TITLE
IllegalArgumentException when Pool initialized with 0 capacity

### ISSUE THREAD

**Issue by kephale** [mastodon-sc/mastodon-collection#3]
```
		final Vertex3Pool vp = new Vertex3Pool( 0 );
		final TrianglePool tp = new TrianglePool( vp, 0 );
```
Then adding a Triangle leads to
```
java.lang.IllegalArgumentException: cannot store more than 59652323 elements
	at org.mastodon.pool.SingleArrayMemPool.append(SingleArrayMemPool.java:34)
	at org.mastodon.pool.MemPool.create(MemPool.java:118)
	at org.mastodon.pool.Pool.create(Pool.java:195)
	at net.imagej.mesh.Vertex3Pool.create(Vertex3Pool.java:42)
	at net.imagej.mesh.stl.BinarySTLFormat.readVector(BinarySTLFormat.java:141)
	at net.imagej.mesh.stl.BinarySTLFormat.readFacet(BinarySTLFormat.java:125)
	at net.imagej.mesh.stl.BinarySTLFormat.readFacets(BinarySTLFormat.java:75)
	at net.imagej.mesh.stl.BinarySTLFormatTest.testReadFacets(BinarySTLFormatTest.java:165)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
```

**Comment by tpietzsch** [comment]
Should be fixed now
